site_name: "ComCat Lab Welcome Guide"
repo_url: https://github.com/ComCatLab/welcome-guide
edit_uri: docs/sources
site_author: "Ugochukwu Nwosu"

nav:
  - Overview:
    - Home: README.md
    - Quickstart: quickstart.md
  - Workflows: workflows.md
  - 'software_pages.md'
  - 'sample_scripts.md'
  - Tutorials:
    - Intro: 'tutorials/index.md'
    - 'tutorials/cccdb.md'
    - 'tutorials/data_transfer.md'
    - 'tutorials/cluster_setup.md'
  - Troubleshooting: 'resources/troubleshooting.md'
  - 'Development Guide':
    - 'Setting Up': 'dev_guide/setup.md'
    - Contributing: 'dev_guide/contributing.md'
    - 'dev_guide/docs.md'

theme: material

docs_dir: docs/sources

site_dir: docs/site

plugins:
- search
